### ISSUE TITLE
Laravel 5.2 

### ISSUE THREAD

**Issue by rakmaster** [tijsverkoyen/CssToInlineStyles#107]
Your package breaks on install with Laravel 5.2. Specifically the dependency for symfony/css-selector 2.x is no longer valid. symfony/css-selector is now on version 3.x

**Comment by barryvdh** [comment]
Any breaking changes? Otherwise we can just bump to `~2.1|~3.0`

**Comment by stof** [comment]
IMO, this issue is on Laravel side: it should allow installing the Symfony CssSelector 2.8 too, which has the same features than 3.0, and will be a LTS version (while 3.0 will not). any code working with Symfony 3.0 is also compatible with Symfony 2.8 (or should be if you haven't messed up with our changes)

And btw, 3.0 is not stable yet.

@barryvdh yes, there is a breaking change in 3.0. The static API is gone.

**Comment by barryvdh** [comment]
Okay, so we can either use `~2.1` with the current code, or use `~2.8|~3.0` with the new Converter class:
```php
//$query = CssSelector::toXPath($rule['selector']); // Removed

$converter = new CssSelectorConverter();
$query = $converter->toXPath($rule['selector']);
```

So best to change this and bump to `v1.6`, or do we want to keep both versions and release Symfony 3 support as `v2`?

**Comment by stof** [comment]
@barryvdh or support 2.3+ and 3.0 at the same time, by detecting which API is usable (with ``class_exists('...\CssSelectorConverter')``, keeping a single maintained version of your library while being compatible with existing LTS versions of Symfony.

**Comment by barryvdh** [comment]
Something like https://github.com/tijsverkoyen/CssToInlineStyles/pull/108 ?

**Comment by tijsverkoyen** [comment]
Was merged.
