### ISSUE TITLE
The Symfony CssSelector class used in CssToInlineStyles' latest release on packagist (v1.5.5) is deprecated

### ISSUE THREAD

**Issue by leileez** [tijsverkoyen/CssToInlineStyles#122]
I'm using CssToInlineStyles in a project and am getting the following error. 
Here's an excerpt of my stack trace:
```
<.../index.php> [unknown] The Symfony\Component\CssSelector\CssSelector class is deprecated since version 2.8 and will be removed in 3.0. Use directly the \Symfony\Component\CssSelector\CssSelectorConverter class instead. in .../lib/vendor/symfony/css-selector/CssSelector.php on line 14
        ...
        on line 165 in file .../lib/vendor/tijsverkoyen/css-to-inline-styles/src/CssToInlineStyles.php
        on line 301 in file .../lib/vendor/composer/ClassLoader.php
        on line 412 in file .../lib/vendor/composer/ClassLoader.php
        on line 14 in file ../lib/vendor/symfony/css-selector/CssSelector.php
```
It'll be awesome if there's a new released version with the updated Symfony class, since I update libraries using composer and don't want to change that manually.

Thanks.

**Comment by agopaul** [comment]
1.5.4 presents the error that you're describing, but 1.5.5 is fine for me.

Maybe symfony/css-selector v.3 wan't stable when you ran ```composer update```?

**Comment by stof** [comment]
@leileez I'm quite sure you are not using CssToInlineStyles 1.5.5. The line 165 in ``src/CssToInlineStyles.php`` does not use the CssSelector anymore in 1.5.5 (this has been moved to a different class). this is the line presenting the error in 1.5.4 though.

So solving the issue is simple: update to the latest version of CssToInlineStyles instead of using an older release
