### ISSUE TITLE
unwanted html entity conversion in HTML attributes values

### ISSUE THREAD

**Issue by quazardous** [tijsverkoyen/CssToInlineStyles#163]
I'm using the inline tool to precompile Twig template.

```twig
<a href="{{ url('change_lost_password', {token: token.token}) }}" class="btn-primary">Change my password</a>
```

and the result is:

```twig
<a href="%7B%7B%20url('change_lost_password',%20%7Btoken:%20token.token%7D)%20%7D%7D" class="btn-primary" style="...">Change my password</a>
```

how can I avoid the `%7B%7B%20` stuff in the href attribute ?

**Comment by stof** [comment]
Well, the issue is that the Twig template is **not** HTML markup. As such, trying to inline styles here is wrong. In your case, it breaks the Twig markup, but it could also break the inlining itself (in case you have classes added dynamically for instance, of ``{% if %}`` blocks around HTML attributes making the Twig markup invalid HTML.

You should perform the inlining on HTML markup, not on a Twig template. This means that the inlining should be done after rendering the template, not before.

**Comment by quazardous** [comment]
Yeah I figure it out... I'll put the inline class call after the rendering stuff....

thx for answering !
