### ISSUE TITLE
Laravel 6 + php8 issue

### ISSUE THREAD

**Issue by yaroslavmo** [tijsverkoyen/CssToInlineStyles#222]
Hello guys.

### Versions:
laravel/framework:                         v6.20.44
tijsverkoyen/css-to-inline-styles:    2.2.4
symfony/css-selector:                    v6.0.2

### Issue explanation
We are using laravel 6 + php 7.4 and recently noticed that `composer install` started throwing an error:

> Problem 1
    - symfony/css-selector is locked to version v6.0.2 and an update of this package was not requested.
    - symfony/css-selector v6.0.2 requires php >=8.0.2 -> your php version (7.4.27) does not satisfy that requirement.
> Problem 2
    - symfony/css-selector v6.0.2 requires php >=8.0.2 -> your php version (7.4.27) does not satisfy that requirement.
    - tijsverkoyen/css-to-inline-styles 2.2.4 requires symfony/css-selector ^2.7 || ^3.0 || ^4.0 || ^5.0 || ^6.0 -> satisfiable by symfony/css-selector[v6.0.2].
    - tijsverkoyen/css-to-inline-styles is locked to version 2.2.4 and an update of this package was not requested.

Investigation showed that this is happening because laravel/framework requires your package as "^2.2.1" which installs 2.2.4. Then your package requires symfony/css-selector as "^2.7 || ^3.0 || ^4.0 || ^5.0 || ^6.0" which installs v6.0.2. Symfony/css-selector requires PHP >=8.0.2 and that is why the composer is throwing that error.

Your 2.2.4 release adds support for PHP 8.1 but breaks it for php7.x users. 
 
I can think of two possible fixes:
1) release your 2.2.4 as a new major version 3.0.0 so "^2.2.1" in framework package does not pull symfony/css-selector version v6.0.2.
2) new patch release v6.20.45 in laravel/framework that instead of pulling "^2.2.1" would make it a fixed version of "2.2.3".

**Comment by stof** [comment]
This is a total misunderstanding of how composer requirements works.

Composer takes the PHP version into account when resolving dependency. So if you want your locked dependencies to be compatible with PHP 7.4, **tell composer about it**. by default, composer resolves dependencies for your current PHP version, but that's configurable: https://getcomposer.org/doc/06-config.md#platform

Adding support for Symfony 6 in this package is definitely not a BC break, because the `"^2.7 || ^3.0 || ^4.0 || ^5.0 || ^6.0` requirement will install v6.0.2 **only** if you tell composer to resolve dependencies for PHP 8.

**Comment by stof** [comment]
Note that when I says "composer resolves dependencies", this refers to running `composer update`. When you run `composer install` with a lock file, composer is not using the locked dependencies only, it does not re-resolve things (as that would defeat the locking)

**Comment by yaroslavmo** [comment]
Of course! Thank you for the explanation.
