### ISSUE TITLE
Responsive issues

### ISSUE THREAD

**Issue by atinder90** [tijsverkoyen/CssToInlineStyles#81]
turned on media queries feature but it didn't worked.
look like it doesn't take into account screen size of media queries.
Tried the same thing with ruby's premailer. It appends media queries in head of html page.
any work around for similar output ?

**Comment by tijsverkoyen** [comment]
Can you provide me with some sample code

**Comment by josh18** [comment]
I'm assuming what he was talking about is that if you are using the setCSS() setting then media queries aren't imported and placed in the html inside a `<style>`. This would be a really handy feature.

**Comment by maxbublik** [comment]
@josh18 @tijsverkoyen Yep, that would be a good feature to include `@media` rules inside `<head>` tag even if these rules originated from a separate css file. 

@atinder90 That is how I workaround this issue. 
Short answer: Wrap your css rules within `<style>` tag and paste it inside your html before passing your html to the inliner.

Long answer: Assume I have `template.html` and css rules stored in `styles.css` file. At this case I do not even need an inliner. Everything just works because any browser grabs styles via `<link>` tag.

```html
<!DOCTYPE html>
<html>
<head>
    ...
    <link href="styles.css" rel="stylesheet" type="text/css">
    ...
</head>
<body>
...
```

And when I need to inline css, here is my inliner script:

```php
$css = file_get_contents(__DIR__.'/styles.css');
$html = file_get_contents(__DIR__.'/template.html');

// replace <link> tag with css
$html = preg_replace('/<link href="styles.css"[^>]+\>/i', '<style type="text/css">'.$css.'</style>', $html);

$inliner = new TijsVerkoyen\CssToInlineStyles\CssToInlineStyles($html);

// use <style> tags in the HTML as the source for css rules
$inliner->setUseInlineStylesBlock(true);

// remove original <style> tags but do not remove @media queries 
$inliner->setStripOriginalStyleTags(true);
$inliner->setExcludeMediaQueries(true);

$inlinedHtml = $inliner->convert();
```

**Comment by tijsverkoyen** [comment]
Media queries will always be stripped
